# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists_ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listplace',
            old_name='place_end',
            new_name='place_lat',
        ),
        migrations.RenameField(
            model_name='listplace',
            old_name='place_init',
            new_name='place_lon',
        ),
    ]
