# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_ms', '0004_auto_20190527_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='estimatedDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
