# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_ms', '0005_auto_20190527_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='estimatedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.IntegerField(),
        ),
    ]
