# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_ms', '0007_auto_20190528_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='order',
        ),
        migrations.RemoveField(
            model_name='listplace',
            name='placeLat',
        ),
        migrations.RemoveField(
            model_name='listplace',
            name='placeLon',
        ),
        migrations.AddField(
            model_name='listplace',
            name='id_place',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='list',
            name='comment',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
    ]
